### ISSUE TITLE
Ajustar layout de fluxo de cadastro de instituição e seus diretores

### ISSUE THREAD

**Issue by carloszan** [poliedros/cisab-app#13]
A tela está funcionando porém precisa de perfumaria.

**Comment by DaniGomes** [comment]
- [ ] Inserir um botão no primeiro tab que redireciona para cadastro de diretor de autarquia
- [ ] Colocar os campos (tipo, responsável e notas) na seção de dados da autarquia
- [ ] Incluir mensagem de feedback ao clicar nos botões
- [ ] Escrever o email para o qual foi enviado os dados da conta

**Comment by MrAndersonMR** [comment]
As alterações de perfumaria já estão feitas, voltei os arquivos como estava quando a Daniela alterou. Quanto a colocar (1) botões, (2) campos e (4) exibir o email, podem ser usados os Caps para os dois primeiros, e o email é com dados então não mexo dados nesse ticket é somente perfumaria. E o último check (3), não sei se entendi bem, e não sei se já existe um Cap pra isso, posteriormente isso pode ser melhor definido.
