### ISSUE TITLE
Testar fluxo de cadastro de instituição e seus diretores

### ISSUE THREAD

**Issue by carloszan** [poliedros/cisab-app#14]
Testes exaustivos nesse fluxo.

O QA deve testar:

- O registro de um novo diretor com o cadastro da senha
- Recebimento do email para registrar a senha
- Tela de registro de senha
- Tela de dados adicionais das instituições.

**Comment by carloszan** [comment]
Teste dia 01/12 na branch 7-tela-de-cadastrar-senha-no-primeiro-acesso:

- A tela de Cadastro de Municipio nao envia requisicao para a API.
- Link magico está errado.
- Tela de primeiro acesso envia a requisicao e o retorno é 401.

**Comment by carloszan** [comment]
A correcao do 1 nao esta sendo trabalhada nessa branch. O 2 foi aberta uma nova issue no cisab-api (https://github.com/poliedros/cisab-api/issues/13). 3 foi resolvido na branch atual.

**Comment by carloszan** [comment]
Primeiro acesso está retornando 400 (bad request)

**Comment by LucasMarcus** [comment]
Teste realizado "O registro de um novo diretor com o cadastro da senha":
1 - Realizado teste com e-mail já cadastrado - lucas@cisab.dev, retornou mensagem de erro "Email already exists".
2 - Realizado teste de envio sem preencher o campo do Município e preenchendo o campo e-mail com um válido, retornando "Instituição deve ter um nome".
3 - Realizado teste de envio preenchendo o campo municipio e o campo e-mail com um e-mail inválido, retornando "E-mail invalido".
4 - Realizado teste com cadastro válido de municipio e e-mail, retornando "Conta(s) criada(s) com sucesso. Um email foi enviado para: lucasmarcus.abreu@gmail.com".
4.1 - Obtido link que seria encaminhado para o e-mail cadastrado no teste 4 - lucasmarcus.abreu@gmail.com, tela com erro "Senha já cadastrada para esse usuário.".

**Comment by LucasMarcus** [comment]
**Teste realizado "O registro de um novo diretor com o cadastro da senha":
FLUXO - Adicionar prefeitura com informações adicionais**
1 - Realizado teste de cadastro de prefeitura com as informações adicionais, retornando "Conta(s) criada(s) com sucesso. Um email foi enviado para: lucas@cisab.com".
2 - Conferido cadastro realizado no teste 1 no postman, dados registros corretamente.

**Comment by LucasMarcus** [comment]
**Teste realizado "O registro de um novo diretor com o cadastro da senha":
FLUXO - Adicionar prefeitura sem informações adicionais, adicionando Autarquia.**
1 - Realizado cadastro da prefeitura com a autarquia sem informações adicionais, retornando "Conta(s) criada(s) com sucesso. Um email foi enviado para: testeautarquia@dev.com, damae@teste.com". Conferido no postman, retornando informações cadastradas corretamente.

**Comment by LucasMarcus** [comment]
**Teste realizado "O registro de um novo diretor com o cadastro da senha":
FLUXO - Adicionar prefeitura com informações adicionais, adicionando Autarquia com informações adicionais.**
1 - Realizado cadastro da prefeitura com informações adicionais e autarquia com informações adicionais, retornando "Conta(s) criada(s) com sucesso. Um email foi enviado para: sp@sp.sjdr, autarquia@dev.com".  COnferido no postman, retornando informações cadastradas corretamente.
