### ISSUE TITLE
Trocar endpoint da listagem de demanda

### ISSUE THREAD

**Issue by LucasMarcus** [poliedros/cisab-app#145]
Alterar endpoint da listagem da demanda de put pra patch

**Comment by carloszan** [comment]
Botao de ediçao do produto

**Comment by DaniGomes** [comment]
```
git fetch origin
git checkout 145-trocar-endpoint-da-listagem-de-demanda
```

**Comment by MrAndersonMR** [comment]
evidência da modificação
![image](https://github.com/poliedros/cisab-app/assets/20261947/99f7f392-9592-4e6e-ad66-c5e755efaede)

**Comment by DaniGomes** [comment]
Pesquisando mais no código, percebemos que esta lógica de estado da demanda está incompleta e não é necessária.
