### ISSUE TITLE
Alterar campo "Código do Produto" de texto para númerico deixando ser criado automaticamente, sem que o usuário tenha que inserir o dado.

### ISSUE THREAD

**Issue by LucasMarcus** [poliedros/cisab-app#158]
Link - https://cisab.zansavio.site:8443/products/create
![image](https://github.com/poliedros/cisab-app/assets/48762861/14328b0e-585a-4d32-bf14-b3bb67ab1599)

**Comment by DaniGomes** [comment]
```
git fetch origin
git checkout 158-alterar-campo-código-do-produto-de-texto-para-númerico-deixando-ser-criado-automaticamente-sem-que-o-usuário-tenha-que-inserir-o-dado
```

**Comment by DaniGomes** [comment]
Dá para usar a rota de produtos para pegar o valor do último código gerado e incrementar 1.

**Comment by MrAndersonMR** [comment]
![image](https://github.com/poliedros/cisab-app/assets/20261947/992d3e4c-dcfd-4987-ac35-c813d971fdfe)
![image](https://github.com/poliedros/cisab-app/assets/20261947/65f0a880-0e66-4fa5-b875-0fd7bb81ccc3)
a lista de produtos incrementado em um
![image](https://github.com/poliedros/cisab-app/assets/20261947/1fa7d8ad-25bc-4b2c-9419-3bb69dcbf5c3)

**Comment by DaniGomes** [comment]
Testei e está funcionando!
