### ISSUE TITLE
Alterar campo "Valor" na tela de cadastro de produtos de númerico para texto

### ISSUE THREAD

**Issue by LucasMarcus** [poliedros/cisab-app#159]
Cisab solicitou que fosse alterado o campo "Valor" na tela de cadastro para realizar o produto de númerico para texto afim de disponibilizar a possibilidade de digitar outros digitos como "1/2".
![image](https://github.com/poliedros/cisab-app/assets/48762861/fe0efa53-b93c-49dc-a643-0583b55e684a)
Link - https://cisab.zansavio.site:8443/products/create

**Comment by DaniGomes** [comment]
```
git fetch origin
git checkout 159-alterar-campo-valor-na-tela-de-cadastro-de-produtos-de-númerico-para-texto
```

**Comment by MrAndersonMR** [comment]
![image](https://github.com/poliedros/cisab-app/assets/20261947/dc4f406a-5463-4633-90b5-f51de5d42a8a)

**Comment by DaniGomes** [comment]
Testei aqui e funcionou perfeitamente. Só apareceram alguns warnings falando para trocar de:

`<g stroke="none" stroke-width={sWidth} fill-rule="evenodd">`

para:

`<g stroke="none" strokeWidth={sWidth} fillRule="evenodd">`
