### ISSUE TITLE
Consertar edição de produto

### ISSUE THREAD

**Issue by DaniGomes** [poliedros/cisab-app#161]
A edição de produto não estava deixando alterar todos os campos.

**Comment by DaniGomes** [comment]
```
git fetch origin
git checkout 161-consertar-edição-de-produto
```

**Comment by MrAndersonMR** [comment]
Quais seriam os campos?

**Comment by DaniGomes** [comment]
Não vamos fazer isso, já que é possível excluir e criar outro produto.
