### ISSUE TITLE
Detalhes e alterações de textos

### ISSUE THREAD

**Issue by DaniGomes** [poliedros/cisab-app#162]
- [x] Alterar texto de "Distância da CISAB" para "Distância do CISAB".
- [x] Alterar ícone de finalizar após preencher a Norma do produto. Atualmente o ícone de finalizar, nesta etapa, está igual o da imagem e deveria ser o ícone de **finalizar**.
- [x] Alterar cor do texto dos campos de email e senha da tela de login e da tela esqueci minha senha. Após realizar a troca da imagem de fundo do sistema, os campos "Email" e "Senha" se encontram claros em relação ao fundo da imagem, fazendo com que o usuário tenha dificuldade em visualizar tais campos.
- [x] Retirar ano do campo Aniversário da Cidade. Cisab solicitou que o campo Aniversário da Cidade possuísse somente a data e mês, sendo necessário retirar a data completa (dia/mês/ano).
- [x] Escrever um subtítulo "Acessórios" na etapa de adição de acessórios, na criação de produtos.

**Comment by DaniGomes** [comment]
`
git fetch origin
git checkout 162-detalhes-e-alterações-de-textos
`

**Comment by LucasMarcus** [comment]
Na tela de visualizar produtos a categoria se encontra com texto minusculo, produto abaixo na criação foi selecionado a categoria "EPI", na tela de visualização a categoria se encontra como "epi".
![image](https://github.com/poliedros/cisab-app/assets/48762861/1a8efa09-d2d7-44f6-b261-416832d0c1cb)

**Comment by LucasMarcus** [comment]
Na tela de criação da sugestão de produto alterar a frase de "O produto criado aqui irá passar por uma validação da CISAB." para "O produto sugerido abaixo passará por uma validação da CISAB antes de ser aprovado".
![image](https://github.com/poliedros/cisab-app/assets/48762861/84873917-ffed-432a-b689-b0736210411f)
Link - https://cisab.zansavio.site:8443/products/suggest

**Comment by MrAndersonMR** [comment]
Das 7 tarefas foram resolvidas 5, as duas não marcadas do enunciado não entendi o que quer dizer

Daniela
1. (V) tradução alterada
2. (X) não entendi, tick é carrapato em inglês - não como seria o ícone e por que razão
3. (V)
![image](https://github.com/poliedros/cisab-app/assets/20261947/89d53830-06a3-47cc-9bd5-e11f54fb4f58)
4. (V)
![image](https://github.com/poliedros/cisab-app/assets/20261947/e9d215ff-3c4f-42d3-b2cb-050633eb036d)
![image](https://github.com/poliedros/cisab-app/assets/20261947/d272462e-60b5-4646-a3d1-864e27ed028a)
![image](https://github.com/poliedros/cisab-app/assets/20261947/b6ba8b4c-af18-4f0a-8ecb-ee2ed9caf365)
5. (X) não entendi, entendo que os acessórios podem não estar claros, mas não entendi qual deve ser a modificação
Lucas
6. (V) lowercase eliminado - eliminado também de counties e disbalitei para que se possa editar o nome do county
7. (V) tradução alterada

**Comment by DaniGomes** [comment]
- [ ] Escrever um subtítulo "Acessórios" na etapa de adição de acessórios, na criação de produtos.
![acessorios](https://github.com/poliedros/cisab-app/assets/26348888/f6325c05-3e55-43b5-b3f3-b5480b9e3bce)

**Comment by DaniGomes** [comment]
2. Na etapa de adição de Normas, existem 2 ícones. O primeiro é para Finalizar o processo, mas está com o ícone da etapa de imagem, o que pode confundir o usuário. Ver o print.
![img](https://github.com/poliedros/cisab-app/assets/26348888/d33c4429-80a8-4229-bf02-7ce6631a664b)
Trocar para o ícone de finalizar, que seria este: 
![image](https://github.com/poliedros/cisab-app/assets/26348888/f0251618-1de8-4cd7-aee1-a3f3d8635118)

**Comment by MrAndersonMR** [comment]
2. (V) Como ao clicar você é enviado para imagem optei por mudar o texto e não o icone
![image](https://github.com/poliedros/cisab-app/assets/20261947/8c34c403-908d-4105-a53a-ce89779525d9)
![image](https://github.com/poliedros/cisab-app/assets/20261947/5a9b5e63-20e7-405f-9d42-5aeacc6a4068)

5. (V) Achei um pouco redundante mas deixei assim:
![image](https://github.com/poliedros/cisab-app/assets/20261947/943b8ba0-2030-491d-a0e2-8a0cd3b77bfc)
