### ISSUE TITLE
Tela para permitir que o gerente edite os dados do município

### ISSUE THREAD

**Issue by DaniGomes** [poliedros/cisab-app#166]
Atualmente o usuário gerente do município consegue visualizar alguns dados de seu município, mas não consegue editar. Creio que esses dados deveriam estar nesta página 
![image](https://github.com/poliedros/cisab-app/assets/26348888/05850792-f9d4-4ac0-af1f-d8f9e38e959c)
porém os botões não estão funcionando.

**Comment by DaniGomes** [comment]
git fetch origin
git checkout 166-criar-tela-para-permitir-que-o-gerente-edite-os-dados-do-município

**Comment by MrAndersonMR** [comment]
Alterações feitas para que o ADM modifique os municípios
![2](https://github.com/poliedros/cisab-app/assets/20261947/000943c9-9399-40a9-8b76-548862124579)
![1](https://github.com/poliedros/cisab-app/assets/20261947/9f842f00-4df4-48cd-beff-bac54c6a3f6d)
![3](https://github.com/poliedros/cisab-app/assets/20261947/2e9854e6-798f-49f8-ae57-b1ca3d811b68)
