### ISSUE TITLE
Puxar dados do IBGE na tela de cadastrar municipios

### ISSUE THREAD

**Issue by carloszan** [poliedros/cisab-app#41]
Os municipios devem ser de MG. Além disso, a API deve retornar um codigo com erro se caso o municipio ja foi cadastrado.

**Comment by DaniGomes** [comment]
Estou tentando usar o componente CapInputAdvanced, mas ele permite a adição de vários valores. Tem como eu permitir somente um valor @MrAndersonMR ?

![image](https://user-images.githubusercontent.com/26348888/216399658-6f26bd46-24fc-4fb0-83cb-f88ebf44aa6c.png)

**Comment by DaniGomes** [comment]
Depois de corrigir o cap para aceitar apenas um valor, falta puxar o dado da população.
