### ISSUE TITLE
Decidir como sera o sidebar de cada user

### ISSUE THREAD

**Issue by LucasMarcus** [poliedros/cisab-app#58]
Foi decidido que essa issue será realizada com a presença de todos.

**Comment by carloszan** [comment]
Precisamos nos reunir e decidir isso o quanto antes.

**Comment by DaniGomes** [comment]
- [ ] Atualizar ícones com base no usuário logado
- [ ] Checar permissões em cada página
- [ ] Checar links do menu se todos estão funcionando
- [ ] Atualizar roles na API
