### ISSUE TITLE
Consertar o input para demand e alterar ContainerAdd para funcionar como deveria

### ISSUE THREAD

**Issue by MrAndersonMR** [poliedros/cisab-app#66]

**Comment by LucasMarcus** [comment]
Realizado teste na tela de norma, deveria aparecer um alert com o que foi inserido no campo da norma porém não apareceu, necessário verificar com @carloszan. Issue será reaberta.

**Comment by LucasMarcus** [comment]
Após deploy alert apareceu corretamente.
