### ISSUE TITLE
Edição de município não está funcionando

### ISSUE THREAD

**Issue by DaniGomes** [poliedros/cisab-app#68]
A edição de município chama a rota `api/counties/63921c339422592591636883` do next e ela está retornando `304 Not Modified`. Acredito que esteja faltando chamar a rota `[PUT] counties/id` na API.

**Comment by DaniGomes** [comment]
O problema, na verdade era que o botão de enviar não estava chamando a rota do next.

**Comment by LucasMarcus** [comment]
Realizado teste na página e identificado que os campos do fomulário "Dados de contato com o municipio" não estão passando valor, ao inserir algum dado e dar o submit ao voltar na página de visualização e de edição os campos alterados permaneceram vazios.

Realizado tentativa de alterar os dados do formulário "Informações sobre o municipio"  e verificado que somente o campo "Nome do municipio" não altera o valor, permanece com o que se encontrava. Demais campos foram alterados os dados e alterou corretamente.

**Comment by DaniGomes** [comment]
A questão do município, irei tratar junto com a issue do IBGE. 
Com relação à primeira observação, parece que não está salvando no banco a segunda seção da página. Irei verificar isso.

**Comment by DaniGomes** [comment]
O campo website não foi desenhado no banco. Os outros estão corrigidos. O problema é que estava referenciando às variáveis erradas. Tem muito código antigo e comentado no componente. Temos que fazer uma limpeza depois.

**Comment by LucasMarcus** [comment]
Realizado novo teste, ao editar algum dado no formulario "DADOS DE CONTATO COM O MUNICÍPIO" é realizado o envio da alteração porém ao retornar na página de edição do mesmo municipi os campos "Endereço, Código postal, Telefone, E-mail e Redes sociais" se apresentam sem valor. Edição foi realizada em um municipio que constava algum valor nesses campos.

**Comment by LucasMarcus** [comment]
Verificado que não havia sido dado deploy e por isso a falha permanecia, após o deploy foi realizado novo teste e confirmado que foi possível realizar alteração.
