### ISSUE TITLE
Tela de cadastrar senha no primeiro acesso

### ISSUE THREAD

**Issue by DaniGomes** [poliedros/cisab-app#7]
Criar a tela que o email irá redirecionar para o cadastro de senha no primeiro acesso. Após definida a senha, o usuário deverá ser redirecionado para a tela de login.

**Comment by DaniGomes** [comment]
- Inserir requisição que valida se usuário já está ativo (is manager active?)
- Mostrar resultado da requisição para usuário (conseguiu cadastrar a senha ou não)
- Redirecionar para o login

**Comment by DaniGomes** [comment]
Funcionalidade feita! Agora tem que testar e partir para perfumria.

**Comment by carloszan** [comment]
@LucasMarcus e eu vamos trabalhar com os testes agora.
