### ISSUE TITLE
Cadastro de funcionários sem validação de campos

### ISSUE THREAD

**Issue by DaniGomes** [poliedros/cisab-app#75]
Campos dos formulários de adição de usuário ao municipio se encontram sem máscaras, sendo possível criar um usuário com um e-mail inválido

**Comment by LucasMarcus** [comment]
Realizado teste na página com tentativa de cadastrar um usuário sem e-mail válido, verificado que não ocorre o submit do formulário somente quando o campo e-mail possui um e-mail válido.

**Comment by LucasMarcus** [comment]
Outros campos ainda se encontram sem máscaras, como "Senha, Nome e Sobrenome".

**Comment by DaniGomes** [comment]
Corrigido em outra issue. Hoje não é possível criar funcionário com email inválido.
