### ISSUE TITLE
Tema escuro não está funcionando para todas as telas

### ISSUE THREAD

**Issue by DaniGomes** [poliedros/cisab-app#76]
Verificado que ao habilitar o modo escuro e ir na página Funcionários - Criar Funcionários o tema volta para o padrão, isso foi identificado somente nesta página outras permanecem com o modo escuro. Isso acontece para o login da Cisab.

**Comment by DaniGomes** [comment]
Ao logar com usuário de prefeitura, algumas telas também voltam para o tema claro, como: Produtos → Criar Produtos, Lista de Produtos

**Comment by LucasMarcus** [comment]
No teste de usuário da prefeitura o correto é que o user não possa acessar a páginas Criar Produto e Lista de Produtos.

**Comment by LucasMarcus** [comment]
Icone "Funcionários" não deve aparecer para o login da Cisab, somente para o usuário da prefeitura.

**Comment by DaniGomes** [comment]
Já contemplado na issue da sidebar.
